backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "content/uploads" # Media files will be stored in the repo under images
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://rtl-school.netlify.app
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "index"
        file: "content/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Button text", name: ctaText, widget: "string" }
          - { label: "Icon grid title", name: iconGridTitle, widget: "string" }
          - { label: "Icons", name: icon, widget: list, fields: [
              { label: "Icon", name: image, widget: "image" },
              { label: "Description", name: text, widget: "string", required: false },
            ] }
      - label: "Courses"
        name: "courses"
        file: "content/courses/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Text section", name: textSection, widget: "markdown" }
          - { label: "Course section title", name: categoryTitle, widget: "string" }
      - label: "Free lesson"
        name: "free-lesson"
        file: "content/courses/free-lesson/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string",  required: false }
          - { label: "Text blocks", name: textContent, widget: list, fields: [
              { label: "Text", name: text, widget: "markdown" },
              { label: "Media", name: media, widget: "file", required: false },
              { label: "Media caption", name: mediaCaption, widget: "string", required: false },
            ] }
      - label: "Schedule"
        name: "schedule"
        file: "content/courses/schedule/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string",  required: false }
      - label: "Course list"
        name: "course-list"
        file: "content/courses/course-list/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string",  required: false }
          - { label: "Text section", name: textContent, widget: "markdown",  required: false }
      - label: "Study online"
        name: "study-online"
        file: "content/courses/study-online/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Text section", name: textSection, widget: "markdown" }
      - label: "Activities"
        name: "activities"
        file: "content/courses/activities/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Pictures", name: imageGridElements, widget: list, fields: [
              { label: "Picture", name: image, widget: "string" },
              { label: "Picture title", name: title, widget: "string" },
            ] }
      - label: "Private lessons"
        name: "private-lessons"
        file: "content/courses/private-lessons/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Text section", name: textSection, widget: "markdown" }
          - { label: "Teacher section title", name: khruuTitle, widget: "string" }
          - { label: "Teachers", name: khruu, widget: list, fields: [
              { label: "Name", name: name, widget: "string" },
              { label: "Portrait", name: portrait, widget: "image" },
              { label: "Education", name: degree, widget: "string" },
              { label: "Experience", name: experience, widget: "string" },
            ] }
      - label: "ED Visa"
        name: "ed-visa"
        file: "content/ed-visa/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Text content", name: textContent, widget: "markdown" }
          - { label: "Visa duration section title", name: durationTitle, widget: "string" }
          - { label: "Visa information cards", name: durationCards, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Subtitle", name: subtitle, widget: "string" },
              { label: "Description", name: description, widget: "markdown" },
            ] }
      - label: "Teachers"
        name: "about-us"
        file: "content/about-us/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string", required: false }
          - { label: "Text content", name: textSection, widget: "markdown" }
          - { label: "People categories", name: peopleSection, widget: list, fields: [
              { label: "Category title", name: title, widget: "string" },
              { label: "People", name: people, widget: list, fields: [
                { label: "Name", name: name, widget: "string" },
                { label: "Portrait", name: portrait, widget: "image" },
              ] }
            ] }
      - label: "Contact"
        name: "contact"
        file: "content/contact/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string", required: false }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string", required: false }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Contact section title", name: contactSquareTitle, widget: "string" }
          - { label: "Contact section content", name: contactSquareDetails, widget: "markdown" }
          - { label: "Address section title", name: addressSquareTitle, widget: "string" }
          - { label: "Address section content", name: addressSquareDetails, widget: "markdown" }
          - { label: "Form section title", name: formSquareTitle, widget: "string" }
          - { label: "Map section title", name: mapSquareTitle, widget: "string" }
          - { label: "Map", name: map, widget: "image" }
          - { label: "Map link", name: mapLink, widget: "string" }
          - { label: "Map alt text", name: mapAltText, widget: "string" }
  - label: "Partials"
    name: "partials"
    files:
      - label: "Map"
        name: "map"
        file: "content/headless_data/map.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Map image", name: image, widget: "image" }
          - { label: "Link", name: link, widget: "string" }
          - { label: "Map alt text", name: alt, widget: "string" }
          - { label: "Text content", name: text, widget: "markdown" }
      - label: "Prices"
        name: "prices"
        file: "content/headless_data/prices.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Prices", name: prices, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Time", name: time, widget: "string" },
              { label: "Price", name: price, widget: "string" },
            ] }
          - { label: "Text content", name: text, widget: "markdown" }
      - label: "Footer"
        name: "footer"
        file: "content/headless_data/footer.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Footer segments", name: segments, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Content", name: content, widget: "markdown" },
            ] }
      - label: "Course information"
        name: "courses"
        file: "content/headless_data/courses.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Main title", name: categoryTitle, widget: "string" }
          - { label: "Course categories", name: categories, widget: list, fields: [
              { label: "Category title", name: title, widget: "string" },
              { label: "Courses", name: courses, widget: list, fields: [
                { label: "Title", name: title, widget: "string" },
                { label: "Description", name: description, widget: "markdown" },
              ] }
            ] }
      - label: "Schedule"
        name: "schedule"
        file: "content/headless_data/schedule.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title for current year", name: currentYear, widget: "string" }
          - { label: "Schedule for current year", name: currentYearSchedule, widget: "image" }
          - { label: "Title for next year", name: nextYear, widget: "string" }
          - { label: "Schedule for next year", name: nextYearSchedule, widget: "image" }
      - label: "Social media buttons"
        name: "social-media"
        file: "content/headless_data/social-media.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Buttons", name: buttons, widget: list, fields: [
              { label: "Icon", name: icon, widget: "image" },
              { label: "Alt text", name: alt, widget: "string" },
              { label: "Link", name: link, widget: "string" },
            ] }
      - label: "Google reviews"
        name: "reviews"
        file: "content/headless_data/reviews.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: title, widget: "string" }
          - { label: "Link to reviews", name: link, widget: "string" }
          - { label: "Grade", name: grade, widget: "string" }
          - { label: "Review count", name: count, widget: "string" }


