backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "content/uploads" # Media files will be stored in the repo under images
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://rtl-school.netlify.app
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Front page"
        name: "index"
        file: "content/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string" }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Button text", name: ctaText, widget: "string" }
          - { label: "Text section", name: textSection, widget: "markdown" }
      - label: "Courses"
        name: "courses"
        file: "content/courses/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string" }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Text section", name: textSection, widget: "markdown" }
          - { label: "Course section title", name: categoryTitle, widget: "string" }
          - { label: "Course categories", name: categories, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Courses", name: courses, widget: list, fields: [
                { label: "Title", name: title, widget: "string" },
                { label: "Description", name: description, widget: "markdown" },
              ] }
            ] }
      - label: "ED Visa"
        name: "ed-visa"
        file: "content/ed-visa/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string" }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Text content", name: textContent, widget: "markdown" }
          - { label: "Visa duration section title", name: durationTitle, widget: "string" }
          - { label: "Visa information", name: durationCards, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Subtitle", name: subtitle, widget: "string" },
              { label: "Description", name: description, widget: "markdown" },
            ] }
  - label: "Partials"
    name: "partials"
    files:
      - label: "Map"
        name: "map"
        file: "content/headless_data/map.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Map image", name: image, widget: "image" }
          - { label: "Map alt text", name: alt, widget: "string" }
          - { label: "Text content", name: text, widget: "markdown" }
      - label: "Prices"
        name: "prices"
        file: "content/headless_data/prices.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Prices", name: prices, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Time", name: time, widget: "string" },
              { label: "Price", name: price, widget: "string" },
            ] }
          - { label: "Text content", name: text, widget: "markdown" }
      - label: "Footer"
        name: "footer"
        file: "content/headless_data/footer.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Footer segments", name: segments, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Content", name: content, widget: "markdown" },
            ] }

