backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "content/uploads" # Media files will be stored in the repo under images
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://rtl-school.netlify.app
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Front page"
        name: "index"
        file: "content/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string" }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Button text", name: ctaText, widget: "string" }
          - { label: "Text section", name: textSection, widget: "markdown" }
      - label: "Courses"
        name: "courses"
        file: "content/courses/_index.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Meta title (SEO)", name: metaTitle, widget: "string" }
          - { label: "Meta description (SEO)", name: metaDescription, widget: "string" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Banner", name: banner, widget: "image" }
          - { label: "Text section", name: textSection, widget: "markdown" }
          - { label: "Course section title", name: categoryTitle, widget: "string" }
          - { label: "Course categories", name: categories, widget: list, fields: [
              { label: "Title", name: title, widget: "string" },
              { label: "Course categories", name: categories, widget: list, fields: [
                { label: "Title", name: title, widget: "string" },
                { label: "Description", name: description, widget: "markdown" },
              ] }
            ] }